import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'SimpleClosure',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        <main className='flex min-h-screen flex-col items-center justify-center p-8'>
          <div className='flex flex-col w-full max-w-6xl items-center justify-center'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
